version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    image: bookstore_app:latest
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  neo4j:
    image: neo4j:latest
    volumes:
        - ./neo4j/logs:/logs
        - ./neo4j/config:/config
        - ./neo4j/data:/data
        - ./neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/12345678
    ports:
        - "7474:7474"
        - "7687:7687"
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: bookstore
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js