spring:
  application:
    name: MainService
  datasource:
    url: jdbc:mysql://db:3306/bookstore
    username: bookstore
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://bookstore:123456@mongo:27017/bookstore
      
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: 12345678

  kafka:
    bootstrap-servers: "kafka:9092"
    consumer:
      group-id: "myGroup"

