spring:
  application:
    name: Online Bookstore Backend
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: bookstore
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
